{% set name = "visionworkbench" %}

{% set version = "3.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/visionworkbench/visionworkbench/archive/refs/tags/{{ version }}.tar.gz
  sha256: ff30577f89978f470d64ae914ab0a3f3496a001ef2a7712c138485aa789b9edb

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake >=3.15
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

  host:
    - libgdal-core
    - llvm-openmp
    - flann
    - openssl
    - libssh2
    - blas
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libopenblas
    - openblas
    - libopencv
    - opencv
    - hdf5
    - libzlib
    - zlib
    - libboost-devel
    - libjpeg-turbo
    - libtiff
    - libpng
    - lz4-c
    - libstdcxx  # [linux]
    - libgcc  # [linux]
    - libcxx  # [osx]
    # The packages below will go to the stereo-pipeline feedstock
    - chrpath  # [linux]
    - libglvnd  # [linux]
    - parallel
    - pbzip2
    - krb5
    - libpdal-core
    #- ale
    #- usgscsm
    - eigen
    - ceres-solver
    #- cspice =67
    #- csm >=3.0.3,<3.0.4
    - libcurl
    - curl
    - gflags
    - glog
    - geotiff
    # - libprotobuf >=4,<5
    # - protobuf >=4,<5
    - libxml2
    - mesalib
    - mysql
    - nlohmann_json
    # The pcl package fails no matter what
    # - pcl
    # - python
    # - python_abi
    - qt-main
    - qwt
    - tbb
    - tbb-devel
    - xerces-c

  run:
    - libgdal-core
    - llvm-openmp
    - flann
    - openssl
    - libssh2
    - blas
    - blas-devel
    - libblas
    - libcblas
    - liblapack
    - liblapacke
    - libopenblas
    - openblas
    - libopencv
    - opencv
    #- proj
    - hdf5
    - libzlib
    - zlib
    - libboost-devel
    - libjpeg-turbo
    - libtiff
    - libpng
    - lz4-c
    - libstdcxx  # [linux]
    - libgcc  # [linux]
    - libcxx  # [osx]
    # The packages below will go to the stereo-pipeline feedstock
    - chrpath  # [linux]
    - libglvnd  # [linux]
    - parallel
    - pbzip2
    - krb5
    - libpdal-core
    #- ale
    #- usgscsm
    - eigen
    - ceres-solver
    #- cspice =67
    #- csm >=3.0.3,<3.0.4
    - libcurl
    - curl
    - gflags
    - glog
    - geotiff
    # - libprotobuf >=4,<5
    # - protobuf >=4,<5
    - libxml2
    - mesalib
    - mysql
    - nlohmann_json
    # The pcl package fails no matter what
    # - pcl
    # - python
    # - python_abi
    - qt-main
    - qwt
    - tbb
    - tbb-devel
    - xerces-c

test:
  commands:
    - echo "Testing for header"
    - test -f $PREFIX/include/vw/Stereo/Algorithms.h  # [unix]
    - if not exist %LIBRARY_INC%\vw\Stereo\Algorithms.h exit 1  # [win]

    - echo "Testing for library"
    - test -f $PREFIX/lib/libVwCore.dylib  # [osx]
    - test -f $PREFIX/lib/libVwCore.so  # [linux]
    - if not exist %LIBRARY_BIN%\VwCore.dll exit 1  # [win]

    - echo "Testing for CLI"
    - test -f $PREFIX/bin/ipmatch  # [unix]
    - if not exist %LIBRARY_BIN%\ipmatch.exe exit 1  # [win]

#    - $PREFIX/bin/hillshade  -# [unix]

about:
  home: https://github.com/visionworkbench/visionworkbench
  summary: 'An image processing and computer vision library published by NASA'
  description: |
    The NASA Vision Workbench is a general purpose image processing and computer vision library. It is used by NASA for processing images of planetary bodies.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/visionworkbench/visionworkbench
  dev_url: https://github.com/visionworkbench/visionworkbench

extra:
  recipe-maintainers:
    - oleg-alexandrov
