{% set name = "visionworkbench" %}

{% set version = "3.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/visionworkbench/visionworkbench/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4f1fcfff3a2ae058496b2b78437195dc073423a57d1a9db05a24782961278a2f

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake >=3.15
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}

  host:
    - blas-devel
    - blis
    - curl
    - eigen
    - flann
    - geotiff
    - hdf5
    - libblas
    - libboost-devel
    - libcurl
    - libgdal 3.9
    - libjpeg-turbo
    - liblapack
    - liblapacke
    - libopencv
    - libopenblas
    - libpng
    - libssh2
    - libtiff
    - libzlib
    - llvm-openmp
    - lz4-c
    - openblas
    - opencv
    - openssl
    - proj
    - zlib
    
  run:
    - blas-devel
    - blis
    - curl
    - eigen
    - flann
    - geotiff
    - hdf5
    - libblas
    - libboost-devel
    - libcurl
    - libgdal 3.9
    - libjpeg-turbo
    - liblapack
    - liblapacke
    - libopencv
    - libopenblas
    - libpng
    - libssh2
    - libtiff
    - libzlib
    - llvm-openmp
    - lz4-c
    - openblas
    - opencv
    - openssl
    - proj
    - zlib

test:
  commands:
    - hillshade $PREFIX/share/vw/tests/tinyDemAN.tif

about:
  home: https://github.com/visionworkbench/visionworkbench
  summary: 'An image processing and computer vision library published by NASA'
  description: |
    The NASA Vision Workbench is a general purpose image processing and computer vision library. It is used by NASA for processing images of planetary bodies.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/visionworkbench/visionworkbench
  dev_url: https://github.com/visionworkbench/visionworkbench

extra:
  recipe-maintainers:
    - oleg-alexandrov
